"""empty message

Revision ID: 261c13656c8c
Revises: d53ed0bfff18
Create Date: 2019-11-11 12:47:41.430005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261c13656c8c'
down_revision = 'd53ed0bfff18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gced_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gced_enabled')
    # ### end Alembic commands ###
