"""empty message

Revision ID: 29c431c803bc
Revises: 938d2342e478
Create Date: 2019-07-17 16:31:08.485954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c431c803bc'
down_revision = '938d2342e478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'classroom', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classroom', type_='unique')
    # ### end Alembic commands ###
