"""empty message

Revision ID: 303f9c5c8ea4
Revises: 4825b030f4f5
Create Date: 2019-05-10 16:25:12.832231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303f9c5c8ea4'
down_revision = '4825b030f4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theme', sa.Column('cover_image', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theme', 'cover_image')
    # ### end Alembic commands ###
