"""empty message

Revision ID: 3225fc61d870
Revises: 825df62ac752
Create Date: 2019-10-18 17:43:50.256997

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from remixvr.project.models import Project
import secrets


# revision identifiers, used by Alembic.
revision = '3225fc61d870'
down_revision = '825df62ac752'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    session = Session(bind=conn)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column(
        'code', sa.String(length=100), nullable=True))
    for item in session.query(Project).filter_by(code=None):
        item.code = secrets.token_hex(3)
    session.commit()
    op.create_unique_constraint(None, 'project', ['code'])
    op.alter_column('project', 'code', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_column('project', 'code')
    # ### end Alembic commands ###
