"""empty message

Revision ID: 37f460a1f4d2
Revises: 1584139036cb
Create Date: 2019-02-28 14:53:48.334389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f460a1f4d2'
down_revision = '1584139036cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tagname', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['userprofile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.create_table('favoritor_assoc',
    sa.Column('favoriter', sa.Integer(), nullable=True),
    sa.Column('favorited_project', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorited_project'], ['project.id'], ),
    sa.ForeignKeyConstraint(['favoriter'], ['userprofile.id'], )
    )
    op.create_table('tag_assoc',
    sa.Column('tag', sa.Integer(), nullable=True),
    sa.Column('article', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article'], ['project.id'], ),
    sa.ForeignKeyConstraint(['tag'], ['tags.id'], )
    )
    op.drop_table('projects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_name', sa.VARCHAR(length=80), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['userprofile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_name')
    )
    op.drop_table('tag_assoc')
    op.drop_table('favoritor_assoc')
    op.drop_table('project')
    op.drop_table('tags')
    # ### end Alembic commands ###
