"""empty message

Revision ID: 3b0a4e9b5e0d
Revises: 303f9c5c8ea4
Create Date: 2019-05-12 21:42:13.424371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b0a4e9b5e0d'
down_revision = '303f9c5c8ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio', 'file_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('video', 'file_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('videosphere', 'file_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('image', 'file_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('photosphere', 'file_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio', 'file_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('video', 'file_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('videosphere', 'file_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('image', 'file_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('photosphere', 'file_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###
