"""empty message

Revision ID: 4239be6902a3
Revises: 43fd0d0dff54
Create Date: 2019-07-25 16:08:05.136418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4239be6902a3'
down_revision = '43fd0d0dff54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('approved', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'approved')
    # ### end Alembic commands ###
