"""empty message

Revision ID: 43fd0d0dff54
Revises: 2eb95b375140
Create Date: 2019-07-24 15:04:26.650762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43fd0d0dff54'
down_revision = '2eb95b375140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('file_type', sa.String(
        length=100), nullable=False))
    op.alter_column('submission', 'author',
                    existing_type=sa.String(100),
                    type_=sa.String(200),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'file_type')
    op.alter_column('submission', 'author',
                    existing_type=sa.String(200),
                    type_=sa.String(100),
                    existing_nullable=True)
    # ### end Alembic commands ###
