"""empty message

Revision ID: 4825b030f4f5
Revises: cf1ff3b8de01
Create Date: 2019-05-03 12:23:28.096638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4825b030f4f5'
down_revision = 'cf1ff3b8de01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'uri',
                    new_column_name='url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'url',
                    new_column_name='uri')
    # ### end Alembic commands ###
