"""empty message

Revision ID: 7da4098364f3
Revises: e70f8759d3c5
Create Date: 2019-05-19 11:08:02.600167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7da4098364f3'
down_revision = 'e70f8759d3c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('space', sa.Column('type', sa.String(
        length=50), nullable=False, server_default='default'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('space', 'type')
    # ### end Alembic commands ###
