"""empty message

Revision ID: 90fdf582f177
Revises: 6d835ab0989d
Create Date: 2019-06-20 14:20:02.355877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90fdf582f177'
down_revision = '6d835ab0989d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder', sa.String(length=512), nullable=True),
    sa.Column('object_filename', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['field.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('object')
    # ### end Alembic commands ###
