"""empty message

Revision ID: 938d2342e478
Revises: b0938babc6f9
Create Date: 2019-07-17 15:06:24.235202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938d2342e478'
down_revision = 'b0938babc6f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('school_name_key', 'school', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('school_name_key', 'school', ['name'])
    # ### end Alembic commands ###
