"""empty message

Revision ID: 9456e85540f7
Revises: 90fdf582f177
Create Date: 2019-06-21 17:42:27.212207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9456e85540f7'
down_revision = '90fdf582f177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object', sa.Column('thumbnail', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object', 'thumbnail')
    # ### end Alembic commands ###
