"""empty message

Revision ID: abb327ba1c51
Revises: dab9687afeeb
Create Date: 2019-04-25 16:31:25.988291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb327ba1c51'
down_revision = 'dab9687afeeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('space', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'space', 'userprofile', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'space', type_='foreignkey')
    op.drop_column('space', 'author_id')
    # ### end Alembic commands ###
