"""empty message

Revision ID: b0938babc6f9
Revises: 6a34df602d57
Create Date: 2019-07-12 15:07:07.656121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0938babc6f9'
down_revision = '6a34df602d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('school_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'userprofile', 'school', ['school_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userprofile', type_='foreignkey')
    op.drop_column('userprofile', 'school_id')
    # ### end Alembic commands ###
