"""empty message

Revision ID: baae27694917
Revises: 9456e85540f7
Create Date: 2019-06-21 17:50:17.274077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baae27694917'
down_revision = '9456e85540f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object', sa.Column('attribute', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object', 'attribute')
    # ### end Alembic commands ###
