"""empty message

Revision ID: c20fc1938b68
Revises: e16738a6b315
Create Date: 2019-10-28 14:47:40.193075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c20fc1938b68'
down_revision = 'e16738a6b315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object', sa.Column('object_files', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('object', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('object', sa.Column('source_id', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object', 'source_id')
    op.drop_column('object', 'source')
    op.drop_column('object', 'object_files')
    # ### end Alembic commands ###
