"""empty message

Revision ID: cf1ff3b8de01
Revises: abb327ba1c51
Create Date: 2019-04-30 13:18:57.612425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf1ff3b8de01'
down_revision = 'abb327ba1c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linked_space_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['field.id'], ),
    sa.ForeignKeyConstraint(['linked_space_id'], ['space.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    # ### end Alembic commands ###
