"""empty message

Revision ID: d53ed0bfff18
Revises: c20fc1938b68
Create Date: 2019-11-04 13:44:11.212184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53ed0bfff18'
down_revision = 'c20fc1938b68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('select',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selected_value', sa.String(), nullable=True),
    sa.Column('possible_values', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['field.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('select')
    # ### end Alembic commands ###
