"""empty message

Revision ID: ec600df7860f
Revises: 4239be6902a3
Create Date: 2019-07-26 16:11:20.647273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec600df7860f'
down_revision = '4239be6902a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity', sa.Column(
        'is_reaction', sa.Boolean(), nullable=True))
    op.execute("""
        UPDATE activity
        SET is_reaction = 'f'
    """)
    op.alter_column('activity', 'is_reaction', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'is_reaction')
    # ### end Alembic commands ###
